# Generated by Django 2.0.10 on 2019-02-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplication',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
